const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// The native ios/ and android/ directories are regenerated by `expo prebuild`
// and churn constantly during native builds (Pods/, build/, .gradle/). Metro
// has no reason to watch them — doing so causes it to treat every build
// artifact write as a source change and forces the app to keep reloading.
config.resolver.blockList = [
  ...(Array.isArray(config.resolver.blockList) ? config.resolver.blockList : [config.resolver.blockList]),
  /ios\/.*/,
  /android\/.*/,
];

module.exports = config;
