import { useMemo, useState } from "react";
import { Modal, Pressable } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import styled from "styled-components/native";
import { radius, spacing } from "../theme/colors";
import { fontFamily } from "../theme/typography";
import { useTheme } from "../theme/ThemeContext";
import { useI18n } from "../i18n/I18nContext";

// A month grid, written here rather than installed.
//
// The obvious move is @react-native-community/datetimepicker, and it is the
// wrong one for this project: ios/ and android/ are generated by prebuild,
// so a new native module means a new binary. Anybody on the build already
// installed would get a JS bundle referencing a module their app does not
// contain, which is a crash on open rather than a missing picker. This has
// no native side and works on whatever build is already there.
//
// Monday-first, because that is the week here — a Sunday-first grid puts
// the weekend in two different places and every date lands a column off
// from where it is reached for.
const MONTHS = {
  fr: ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
  en: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
};
const WEEKDAY_INITIALS = {
  fr: ["L", "M", "M", "J", "V", "S", "D"],
  en: ["M", "T", "W", "T", "F", "S", "S"],
};

const startOfDay = (date) => {
  const copy = new Date(date);
  copy.setHours(0, 0, 0, 0);
  return copy;
};

// Monday = 0.
const mondayIndex = (jsDay) => (jsDay + 6) % 7;

export function CalendarPicker({ visible, value, onSelect, onClose, minDate }) {
  const { colors } = useTheme();
  const { language, t } = useI18n();
  const lang = language === "en" ? "en" : "fr";

  const today = startOfDay(new Date());
  const floor = minDate ? startOfDay(minDate) : today;

  // Opens on the month of whatever is already chosen, so correcting a date
  // does not start by scrolling back to where you were.
  const [cursor, setCursor] = useState(() =>
    value ? new Date(value.getFullYear(), value.getMonth(), 1) : new Date(today.getFullYear(), today.getMonth(), 1),
  );

  const cells = useMemo(() => {
    const year = cursor.getFullYear();
    const month = cursor.getMonth();
    const firstOffset = mondayIndex(new Date(year, month, 1).getDay());
    const daysInMonth = new Date(year, month + 1, 0).getDate();

    const list = [];
    for (let i = 0; i < firstOffset; i += 1) list.push(null);
    for (let day = 1; day <= daysInMonth; day += 1) {
      list.push(new Date(year, month, day));
    }
    return list;
  }, [cursor]);

  const sameDay = (a, b) =>
    a &&
    b &&
    a.getDate() === b.getDate() &&
    a.getMonth() === b.getMonth() &&
    a.getFullYear() === b.getFullYear();

  // An event you cannot attend is not worth offering. The month arrow is
  // disabled rather than hidden so the control does not move around.
  const canGoBack =
    new Date(cursor.getFullYear(), cursor.getMonth(), 1) >
    new Date(floor.getFullYear(), floor.getMonth(), 1);

  const step = (months) =>
    setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + months, 1));

  return (
    <Modal visible={visible} animationType="fade" transparent onRequestClose={onClose}>
      <Backdrop onPress={onClose} />
      <Centre pointerEvents="box-none">
        <Card>
          <Head>
            <NavButton onPress={() => canGoBack && step(-1)} disabled={!canGoBack} hitSlop={8}>
              <Ionicons
                name="chevron-back"
                size={20}
                color={canGoBack ? colors.text : colors.border}
              />
            </NavButton>
            <MonthLabel>
              {MONTHS[lang][cursor.getMonth()]} {cursor.getFullYear()}
            </MonthLabel>
            <NavButton onPress={() => step(1)} hitSlop={8}>
              <Ionicons name="chevron-forward" size={20} color={colors.text} />
            </NavButton>
          </Head>

          <WeekRow>
            {WEEKDAY_INITIALS[lang].map((initial, index) => (
              <WeekCell key={`${initial}-${index}`}>
                <WeekLabel>{initial}</WeekLabel>
              </WeekCell>
            ))}
          </WeekRow>

          <Grid>
            {cells.map((date, index) => {
              if (!date) return <DayCell key={`blank-${index}`} />;
              const disabled = date < floor;
              const selected = sameDay(date, value);
              return (
                <DayCell key={date.toISOString()}>
                  <Day
                    selected={selected}
                    disabled={disabled}
                    onPress={() => !disabled && onSelect(date)}
                  >
                    <DayLabel selected={selected} disabled={disabled}>
                      {date.getDate()}
                    </DayLabel>
                    {sameDay(date, today) && !selected ? <TodayDot /> : null}
                  </Day>
                </DayCell>
              );
            })}
          </Grid>

          <CloseRow onPress={onClose}>
            <CloseLabel>{t("calendarClose")}</CloseLabel>
          </CloseRow>
        </Card>
      </Centre>
    </Modal>
  );
}

const Backdrop = styled(Pressable)`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.4);
`;

const Centre = styled.View`
  flex: 1;
  align-items: center;
  justify-content: center;
  padding: ${spacing.lg}px;
`;

const Card = styled.View`
  width: 100%;
  max-width: 360px;
  padding: ${spacing.md}px;
  border-radius: ${radius.xl}px;
  background-color: ${(props) => props.theme.background};
`;

const Head = styled.View`
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
  margin-bottom: ${spacing.md}px;
`;

const NavButton = styled(Pressable)`
  width: 38px;
  height: 38px;
  align-items: center;
  justify-content: center;
  border-radius: ${radius.pill}px;
`;

const MonthLabel = styled.Text`
  font-family: ${fontFamily.semiBold};
  font-size: 15.5px;
  text-transform: capitalize;
  color: ${(props) => props.theme.text};
`;

const WeekRow = styled.View`
  flex-direction: row;
  margin-bottom: ${spacing.xs}px;
`;

const WeekCell = styled.View`
  flex: 1;
  align-items: center;
`;

const WeekLabel = styled.Text`
  font-family: ${fontFamily.semiBold};
  font-size: 11px;
  color: ${(props) => props.theme.textMuted};
`;

const Grid = styled.View`
  flex-direction: row;
  flex-wrap: wrap;
`;

// A seventh of the row, so the columns line up with the weekday header
// whatever the month does.
const DayCell = styled.View`
  width: 14.28%;
  align-items: center;
  padding: 2px 0;
`;

const Day = styled(Pressable)`
  width: 40px;
  height: 40px;
  align-items: center;
  justify-content: center;
  border-radius: ${radius.pill}px;
  background-color: ${(props) =>
    props.selected ? props.theme.primary : "transparent"};
`;

const DayLabel = styled.Text`
  font-family: ${(props) =>
    props.selected ? fontFamily.bold : fontFamily.medium};
  font-size: 14.5px;
  color: ${(props) =>
    props.selected
      ? "#ffffff"
      : props.disabled
        ? props.theme.border
        : props.theme.text};
`;

const TodayDot = styled.View`
  position: absolute;
  bottom: 6px;
  width: 4px;
  height: 4px;
  border-radius: ${radius.pill}px;
  background-color: ${(props) => props.theme.primary};
`;

const CloseRow = styled(Pressable)`
  align-items: center;
  padding: ${spacing.sm}px;
  margin-top: ${spacing.xs}px;
`;

const CloseLabel = styled.Text`
  font-family: ${fontFamily.semiBold};
  font-size: 14px;
  color: ${(props) => props.theme.textMuted};
`;
